#!/bin/sh
export PATH=/opt/gcc-4.3-ls232/bin/:$PATH
#export PATH=/opt/gcc-4.4-64-gnu/bin/:$PATH

#export MAKEFLAGS='CC=mipsel-linux-gcc\ -g'
make ARCH=mips CROSS_COMPILE=mipsel-linux- -j4 "$@"
#make ARCH=mips CROSS_COMPILE=mips64el-linux- -j4 "$@"
