# LOONGSON Platform Support
snd-soc-ls1a-objs := ls1a-pcm.o
snd-soc-ls1a-ac97-objs := ls1a-ac97.o

obj-$(CONFIG_SND_LS1A_SOC) += snd-soc-ls1a.o
obj-$(CONFIG_SND_LS1A_SOC_AC97) += snd-soc-ls1a-ac97.o

# LS1A Machine Support
snd-ls1a-objs := ls1a.o

obj-$(CONFIG_SND_LS1A) += snd-ls1a.o

